### ISSUE TITLE
Pending for PR dependencies

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#126]
@scorninpc could you please merge those 4 pull reuests because I want to implement new features about drawing area and worried about future conflicts because I'm using current master branch as the source for each new feature.

I have tested them all

**Comment by scorninpc** [comment]
Yes i can, but i need a working code to test if pr works and if dont break another things

**Comment by scorninpc** [comment]
look [d47081](https://github.com/d47081), I really appreciate your willingness to use, test and contribute to the project

but you need to understand that this is not my main job, I have other projects, another company to take care of, and many other things

your issues and PRs are confusing, there's rarely any logs, code or anything that I can just run it and see the same error you're seeing, and every time I need to imagine your code, code it, just to test if something wrong occurs, and try to imagine if that is the problem, it takes a lot of time

your attached code is not a working code, it's just a object creation and a dump. I cannot run this and see what this is for

my choice in using PHP-CPP was precisely to be able to open a project that even someone with little knowledge of C could help with, but for that I need people to also help me maintain it

I hope you understand that maintaining a project is complicated and delicate, especially because you also have some great projects, and that you don't give up on contributing

**Comment by scorninpc** [comment]
> _e.g. I have [one more feature](https://github.com/d47081/php-gtk3/commit/53c7247d848e6da12983a63abedea2ad341ddd8f) but it's not work for me as expected, so did not sent as PR yet_

In generaly, this is the problem. I never used `gtk_label_select_region` so i dont know how/where/when use it. with some code, some example, prints, videos, anything, can help alot
